# Faster container-based infrastructure
sudo: false

language: python

python:
  - "3.5"
  - "3.6"

install:
  - pip install -e .[tests] isort unify flake8
  - pip freeze

script:
  - pytest
  - flake8
  - isort --check-only --recursive asgiref tests
  - unify --check-only --recursive --quote \" asgiref tests
