# Faster container-based infrastructure
sudo: false

language: python

python:
  - "3.5"
  - "3.6"

install:
  - pip install -e .[tests] isort unify
  - pip freeze

script:
  - pytest
  - isort --check-only --recursive asgiref
  - unify --check-only --recursive --quote \" asgiref/
