# Faster container-based infrastructure
sudo: false

language: python

python:
  - "3.6"
  - "3.5"

install:
  - pip install -e .[tests]
  - pip freeze

script:
  - pytest

stages:
  - lint
  - test
  - name: release
    if: tag IS present

jobs:
  include:
    - python: "3.7"
      dist: xenial
      sudo: required

    - stage: lint
      install: pip install -U -e .[tests] black pyflakes isort
      script:
        - pyflakes asgiref tests
        - black --check asgiref tests
        - isort --check-only --diff --recursive asgiref tests

    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        user: andrewgodwin_bot
        on:
          tags: true
        distributions: sdist bdist_wheel
        password:
          secure: Bt6uFOAf2n9D5z06Orv8w6a3zU86mkpA9wspLsu8AIJ2kZx61bpO+27vHvJFyVpkEW+EerzUY9sOq02jd8EhzHL86wcM5zgXyDYhlZ6CxYxU9vFXrBmLzC/rrGbirArseXnDZY5ulPnuRBFxJyqJ2mZeDKjn+qoa8qe364si/wPDWs9YjQFSbT6lJz0MVIVKQNHw5iAXBsQ+yQewjbNPo4nOd81kqlO8Bg/Xpu85/rHjim8zG9PWAMUnueIMyYSTUTXSmZFRR+3viJ7HZz7o0HxepokkpLODdvbUKnKi2fdQAa4fAlInqFf4gSaLN8f+Ch5aDFeDmz7FVcwUbKEmWo67/lzb0NQwiYz11O+K78xFPRHopCljR3VFpCSxw/oJuLRlbElXO0q8JLznKVdgdoFqSV4/W7HgXXdYuDjcYWHiYHHc1t/JoOF3bRkjRu7Ax9HwmEi1RLL4ou5G/lT60Pd50FRcLV788AYw7CiZFewRyXjJSB59Crqt05Eyl0Wtynd1JwHDkJC2SYuWfqRHYM+oicqxbSyecjbMu8vDD56soDEeM/oHojBo4IpEYtGYHndGvnmtOuPpiKNpxxZC6ipghrv74s0Btw9HaI8SW1/G3EDCudL5rd7X9gdMFESdp/WshKlr4treEYfPRkZcuh3WW9CE2QS0IiCXoWk60AA=
